version: '3.8'

services:
  dynamodb-cmyk-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    environment:
      - AWS_REGION=${REGION:-local}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-key-id}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-secret}
    container_name: dynamodb-cmyk-local
    image: "amazon/dynamodb-local:1.20.0"
    networks:
      - cmyk_network
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    volumes:
      - "./ddb/data:/home/dynamodblocal/data"

networks:
  cmyk_network:
    name: cmyk_network