#!/bin/bash -x

set -a; source .env.local; set +a

AWS_REGION=${REGION:-local}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-key-id}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-secret}

export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export WORK_DIR
export DYNAMO_ENDPOINT

docker-compose -f docker-compose.yml up -d
./ddb/ddb-schemas/create-dynamodb-tables.sh ./ddb/ddb-schemas/users